/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiProduceSongRouteImport } from './routes/api/ai.produce-song'
import { Route as ApiAiEnhanceVocalRouteImport } from './routes/api/ai.enhance-vocal'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiProduceSongRoute = ApiAiProduceSongRouteImport.update({
  id: '/api/ai/produce-song',
  path: '/api/ai/produce-song',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEnhanceVocalRoute = ApiAiEnhanceVocalRouteImport.update({
  id: '/api/ai/enhance-vocal',
  path: '/api/ai/enhance-vocal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/enhance-vocal': typeof ApiAiEnhanceVocalRoute
  '/api/ai/produce-song': typeof ApiAiProduceSongRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/enhance-vocal': typeof ApiAiEnhanceVocalRoute
  '/api/ai/produce-song': typeof ApiAiProduceSongRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/enhance-vocal': typeof ApiAiEnhanceVocalRoute
  '/api/ai/produce-song': typeof ApiAiProduceSongRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/ai/chat'
    | '/api/ai/enhance-vocal'
    | '/api/ai/produce-song'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/ai/chat'
    | '/api/ai/enhance-vocal'
    | '/api/ai/produce-song'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/ai/chat'
    | '/api/ai/enhance-vocal'
    | '/api/ai/produce-song'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiEnhanceVocalRoute: typeof ApiAiEnhanceVocalRoute
  ApiAiProduceSongRoute: typeof ApiAiProduceSongRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/produce-song': {
      id: '/api/ai/produce-song'
      path: '/api/ai/produce-song'
      fullPath: '/api/ai/produce-song'
      preLoaderRoute: typeof ApiAiProduceSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/enhance-vocal': {
      id: '/api/ai/enhance-vocal'
      path: '/api/ai/enhance-vocal'
      fullPath: '/api/ai/enhance-vocal'
      preLoaderRoute: typeof ApiAiEnhanceVocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiEnhanceVocalRoute: ApiAiEnhanceVocalRoute,
  ApiAiProduceSongRoute: ApiAiProduceSongRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
